### PR TITLE
Little changes, added more devices

### PR DESCRIPTION
**Pull request by AKuHAK**
Found almost all Samsung devices which uses this board.
There is also XiaoLajiao LA2-s (Beidou LA2-S) phone with pxa1908
And some more devices on pxa1088:
Lenovo A828T
Onda V819 4G
HP Slate 6 VoiceTab
Lenovo U828T G3

### CODE REVIEW

**Comment by osm0sis** [comment]
Nice! I didn't realize Xcover 3 was actually the pxa1908 and not 1088 like the others! I think I'll take it one step further and just call it pxa-mkbootimg, etc. all around.

What was the issue with -O3? Seems to work fine here so I'd prefer that stay enabled.

**Comment by osm0sis** [comment]
Onda V819 4G is apparently PXA1920, as is Lenovo A788T - they seem to be AOSP standard again. Well done Marvell. 😉

**Comment by AKuHAK** [comment]
With o3 and newest gcc it errorred on fgets (no checks for failing) I was
lazy to fix it and just suppressed it ))

ср, 28 июн. 2017 г., 16:47 Chris Renshaw <notifications@github.com>:

**Comment by osm0sis** [comment]
I'm not seeing fgets anywhere in this repo, can you point me to what you're talking about?

**Comment by AKuHAK** [comment]
Oh im sorry i mean fread

ср, 28 июн. 2017 г., 17:22 Chris Renshaw <notifications@github.com>:

**Comment by osm0sis** [comment]
Ah yes, I've got a patch for that in my main mkbootimg repo, I'll bring it over. 👍

**Comment by AKuHAK** [comment]
Thanks )) i didnt saw that commit...

ср, 28 июн. 2017 г., 18:03 Chris Renshaw <notifications@github.com>:

**Comment by AKuHAK** [comment]
Hi again. I found one more 'unknown' value. It is 0x02800000. Its for kernels SM-J110F and SM-J110G. So you can update your kitchen cause now these kernels are recognized as AOSP in image kitchen. You can check this here:
https://yadi.sk/d/uiglXj-33MCMPj
Best regards! :)

**Pull request merged**
