### PR TITLE
Update pxa1908-dtbtool.c

### PR DESCRIPTION
**Pull request by luka177**
Like drebrez, fixed if condition.

### CODE REVIEW

**Comment by osm0sis** [comment]
Thanks!

**Comment by drebrez** [comment]
@osm0sis when you find some time, please tag a new release, so we can properly package it in postmarketOS. Thanks

**Comment by osm0sis** [comment]
Yep, already told you I would when I got home. Chill, Winston.

**Comment by osm0sis** [comment]
And pushed!

Cheers, fellas!

**Pull request merged**
